name: CI/CT workflow for Python FastAPI service docker image

on:
  push:

jobs:
  set_stage:
    name: Determine Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Linting and auto-formatting Python files
        uses: MGTheTrain/github-actions/.github/actions/linting-and-auto-formatting-for-python@main
        with:
          PYTHON_VERSION: "3.11"
          WORKING_DIRECTORY: ./
          GH_TOKEN: ${{ inputs.GH_TOKEN }}