name: CI/CT workflow for Python FastAPI service docker image

on:
  pull_request:
    branches: 
      - develop
      - master

jobs:
  set_stage:
    name: Determine Stage
    runs-on: ubuntu-latest
    steps:
      - name: Set revision_number by branch and semantic_version
        id: branch_check
        run: |
          echo "Running on branch ${{ github.base_ref }}"
          if [ "${{ github.base_ref }}" == "master" ]; then
            echo "::set-output name=revision_number::prerelease${{ github.run_number }}"
          elif [ "${{ github.base_ref }}" == "develop" ]; then
            echo "::set-output name=revision_number::dev${{ github.run_number }}"
          fi
          semantic_version=$(cat version)
          echo "::set-output name=semantic_version::$semantic_version"
      - name: Print Semantic version
        run: echo "revision_number for branch '${{ github.base_ref }}' is '${{ steps.branch_check.outputs.semantic_version }}'"
      - name: Print Revision number
        run: echo "semantic_version for branch '${{ github.base_ref }}' is '${{ steps.branch_check.outputs.revision_number }}'"
    outputs:
      revision_number: ${{ steps.branch_check.outputs.revision_number }}
      semantic_version: ${{ steps.branch_check.outputs.semantic_version }}
  ci-ct-job-for-python-fast-api-services:
    runs-on: ubuntu-latest
    needs: [set_stage]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: CI/CT Action for Python Backend Services
        uses: MGTheTrain/github-actions/.github/actions/ci-ct-action-for-python-backend-services@main
        with:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORGANIZATION_ID: ${{ secrets.SNYK_ORGANIZATION_ID }}
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }} 
          ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
          PYTHON_VERSION: "3.11"
          WORKING_DIRECTORY: ./
          DOCKER_IMAGE_NAME: python-hello-world-service:${{ needs.set_stage.outputs.semantic_version }}-${{ needs.set_stage.outputs.revision_number }}
